<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAP-C-4153" name="testScripts.ScantoBox_CartLabel_Dispatch" tests="1" failures="0" timestamp="16 May 2023 14:58:02 GMT" time="63.312" errors="1">
  <testcase name="scan_to_box_cart_picking" time="63.312" classname="testScripts.ScantoBox_CartLabel_Dispatch">
    <error type="java.lang.Exception" message="(//td[@id=&#039;DashboardPO_GateInNum&#039;])[1] not found">
      <![CDATA[java.lang.Exception: (//td[@id='DashboardPO_GateInNum'])[1] not found
at testScripts.TestNGlisteners.onTestFailure(TestNGlisteners.java:62)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:67)
at org.testng.internal.Invoker.runTestListeners(Invoker.java:1389)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:636)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at testScripts.VisibilityMain.main(VisibilityMain.java:68)
]]>
    </error>
  </testcase> <!-- scan_to_box_cart_picking -->
</testsuite> <!-- testScripts.ScantoBox_CartLabel_Dispatch -->
