<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAP-C-4153" name="testScripts.ReturnOrder" tests="1" failures="0" timestamp="16 May 2023 14:58:02 GMT" time="120.546" errors="1">
  <testcase name="returnOrder_Inbound" time="120.546" classname="testScripts.ReturnOrder">
    <error type="java.lang.Exception" message="//input[@id=&#039;AssignPod_VehicleNumber_Checkbox 0&#039;] not found">
      <![CDATA[java.lang.Exception: //input[@id='AssignPod_VehicleNumber_Checkbox 0'] not found
at testScripts.TestNGlisteners.onTestFailure(TestNGlisteners.java:62)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:67)
at org.testng.internal.Invoker.runTestListeners(Invoker.java:1389)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:636)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at testScripts.VisibilityMain.main(VisibilityMain.java:68)
]]>
    </error>
  </testcase> <!-- returnOrder_Inbound -->
</testsuite> <!-- testScripts.ReturnOrder -->
