<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-282TSLQ" name="testScripts.Inbound_OrderForm" tests="14" failures="0" timestamp="9 Aug 2021 06:56:27 GMT" time="279.977" errors="12">
  <testcase name="vehicleCreatioN" time="0.831" classname="testScripts.Inbound_OrderForm"/>
  <testcase name="optimization_skip" time="0.000" classname="testScripts.Inbound_OrderForm">
    <error type="java.lang.Throwable" message="Method OrderForm.optimization_skip()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method OrderForm.optimization_skip()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at testScripts.VisibilityMain.main(VisibilityMain.java:24)
]]>
    </error>
  </testcase> <!-- optimization_skip -->
  <testcase name="assignPOD" time="0.000" classname="testScripts.Inbound_OrderForm">
    <error type="java.lang.Throwable" message="Method OrderForm.assignPOD()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method OrderForm.assignPOD()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at testScripts.VisibilityMain.main(VisibilityMain.java:24)
]]>
    </error>
  </testcase> <!-- assignPOD -->
  <testcase name="Random_pick" time="0.000" classname="testScripts.Inbound_OrderForm">
    <error type="java.lang.Throwable" message="Method OrderForm.Random_pick()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method OrderForm.Random_pick()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at testScripts.VisibilityMain.main(VisibilityMain.java:24)
]]>
    </error>
  </testcase> <!-- Random_pick -->
  <testcase name="podGeneration1" time="0.000" classname="testScripts.Inbound_OrderForm">
    <error type="java.lang.Throwable" message="Method OrderForm.podGeneration1()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method OrderForm.podGeneration1()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at testScripts.VisibilityMain.main(VisibilityMain.java:24)
]]>
    </error>
  </testcase> <!-- podGeneration1 -->
  <testcase name="binnerAssignment" time="0.000" classname="testScripts.Inbound_OrderForm">
    <error type="java.lang.Throwable" message="Method OrderForm.binnerAssignment()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method OrderForm.binnerAssignment()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at testScripts.VisibilityMain.main(VisibilityMain.java:24)
]]>
    </error>
  </testcase> <!-- binnerAssignment -->
  <testcase name="inbOrderform" time="239.096" classname="testScripts.Inbound_OrderForm">
    <error type="org.openqa.selenium.TimeoutException" message="Expected condition failed: waiting for testScripts.CommonFunctions$1@76adb233 (tried for 3 second(s) with 3000 milliseconds interval)">
      <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for testScripts.CommonFunctions$1@76adb233 (tried for 3 second(s) with 3000 milliseconds interval)
	at testScripts.TestNGlisteners.onTestFailure(TestNGlisteners.java:54)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1693)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1677)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at testScripts.VisibilityMain.main(VisibilityMain.java:24)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@id='PO_custref']"}
  (Session info: chrome=92.0.4515.131)
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'DESKTOP-282TSLQ', ip: '192.168.0.112', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 92.0.4515.131, chrome: {chromedriverVersion: 92.0.4515.107 (87a818b10553..., userDataDir: C:\Users\WDSI\AppData\Local...}, goog:chromeOptions: {debuggerAddress: localhost:53132}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 4a2c903ec388c90bdf823c88e5b57468
*** Element info: {Using=xpath, value=//input[@id='PO_custref']}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:319)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:421)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:311)
	at testScripts.CommonFunctions$1.apply(CommonFunctions.java:372)
	at testScripts.CommonFunctions$1.apply(CommonFunctions.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:248)
	at testScripts.CommonFunctions.fluentWaitxpath(CommonFunctions.java:370)
	at testScripts.Inbound_OrderForm.inbOrderform(OrderForm.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	... 16 more
]]>
    </error>
  </testcase> <!-- inbOrderform -->
  <testcase name="pickerassignment" time="0.000" classname="testScripts.Inbound_OrderForm">
    <error type="java.lang.Throwable" message="Method OrderForm.pickerassignment()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method OrderForm.pickerassignment()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at testScripts.VisibilityMain.main(VisibilityMain.java:24)
]]>
    </error>
  </testcase> <!-- pickerassignment -->
  <testcase name="captureParentDetails" time="40.050" classname="testScripts.Inbound_OrderForm"/>
  <testcase name="AlternativeBin_Picking" time="0.000" classname="testScripts.Inbound_OrderForm">
    <error type="java.lang.Throwable" message="Method OrderForm.AlternativeBin_Picking()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method OrderForm.AlternativeBin_Picking()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at testScripts.VisibilityMain.main(VisibilityMain.java:24)
]]>
    </error>
  </testcase> <!-- AlternativeBin_Picking -->
  <testcase name="dispatch" time="0.000" classname="testScripts.Inbound_OrderForm">
    <error type="java.lang.Throwable" message="Method OrderForm.dispatch()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method OrderForm.dispatch()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at testScripts.VisibilityMain.main(VisibilityMain.java:24)
]]>
    </error>
  </testcase> <!-- dispatch -->
  <testcase name="outboundCREATEREQUEST1" time="0.000" classname="testScripts.Inbound_OrderForm">
    <error type="java.lang.Throwable" message="Method OrderForm.outboundCREATEREQUEST1()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method OrderForm.outboundCREATEREQUEST1()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at testScripts.VisibilityMain.main(VisibilityMain.java:24)
]]>
    </error>
  </testcase> <!-- outboundCREATEREQUEST1 -->
  <testcase name="shortpick" time="0.000" classname="testScripts.Inbound_OrderForm">
    <error type="java.lang.Throwable" message="Method OrderForm.shortpick()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method OrderForm.shortpick()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at testScripts.VisibilityMain.main(VisibilityMain.java:24)
]]>
    </error>
  </testcase> <!-- shortpick -->
  <testcase name="binning" time="0.000" classname="testScripts.Inbound_OrderForm">
    <error type="java.lang.Throwable" message="Method OrderForm.binning()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method OrderForm.binning()[pri:0, instance:testScripts.Inbound_OrderForm@4e04a765] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at testScripts.VisibilityMain.main(VisibilityMain.java:24)
]]>
    </error>
  </testcase> <!-- binning -->
</testsuite> <!-- testScripts.Inbound_OrderForm -->
